// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package buttons

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"fmt"
	"github.com/chrisbward/templstrap.io/pkg/base"
	"strings"
)

type ButtonClassType string

const PrimaryButton ButtonClassType = "btn-primary"
const SecondaryButton ButtonClassType = "btn-secondary"
const SuccessButton ButtonClassType = "btn-success"
const DangerButton ButtonClassType = "btn-danger"
const WarningButton ButtonClassType = "btn-warning"
const InfoButton ButtonClassType = "btn-info"
const LightButton ButtonClassType = "btn-light"
const DarkButton ButtonClassType = "btn-dark"

type ButtonStyleType string

const SolidButton ButtonStyleType = ""
const OutlineButton ButtonStyleType = "outline"

type ButtonSizeType string

const SmallButton ButtonSizeType = "sm"
const LargeButton ButtonSizeType = "lg"

type ButtonType string

const SubmitButton ButtonType = "submit"
const ResetButton ButtonType = "reset"

type ButtonElementType string

const AnchorButtonType ButtonElementType = "a"
const ButtonButtonType ButtonElementType = "button"
const InputButtonType ButtonElementType = "input"

type ButtonProps struct {
	base.ElementProps
	IsDisabled        bool
	ButtonType        ButtonType
	ButtonClassType   ButtonClassType
	Style             ButtonStyleType
	Size              ButtonSizeType
	ButtonElementType ButtonElementType
}

const RootClassName = "btn"

func (bp *ButtonProps) BuildClassNames() (classNames string) {

	classValues := []string{RootClassName}
	classValues = append(classValues, string(bp.ButtonClassType))

	if bp.AdditionalClasses != nil {
		classValues = append(classValues, bp.AdditionalClasses...)
	}

	if bp.Size != "" {
		buttonSizeClass := fmt.Sprintf("btn-%s", bp.Size)
		classValues = append(classValues, buttonSizeClass)
	}

	classNames = strings.Join(classValues, " ")

	return
}

func Show(props ButtonProps) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if props.ButtonElementType == "" || props.ButtonElementType == ButtonButtonType {
			var templ_7745c5c3_Var2 = []any{props.BuildClassNames()}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<button type=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(props.ButtonType)))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ.CSSClasses(templ_7745c5c3_Var2).String()))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.IsDisabled {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" disabled")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if props.ButtonElementType == AnchorButtonType {
			var templ_7745c5c3_Var3 = []any{props.BuildClassNames()}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var3...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ.CSSClasses(templ_7745c5c3_Var3).String()))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" href=\"#\" role=\"button\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
