// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package htmxdemoform

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/chrisbward/templstrap.io/pkg/base"
	"github.com/chrisbward/templstrap.io/pkg/components/alerts"
	"github.com/chrisbward/templstrap.io/pkg/forms/form"
	"github.com/chrisbward/templstrap.io/pkg/forms/formfield"
	"github.com/chrisbward/templstrap.io/pkg/forms/formlabel"
	"github.com/chrisbward/templstrap.io/pkg/forms/inputfield"
	"github.com/chrisbward/templstrap.io/testsuite/entities"
	"net/http"
)

type HTMXDemoFormProps struct {
	FormFields           map[string]*entities.FormField
	FormFieldOrder       []string
	IncorrectCredentials bool
}

func Show(props HTMXDemoFormProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			if props.IncorrectCredentials {
				templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<p>Invalid username or password</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return nil
				})
				templ_7745c5c3_Err = alerts.Show(alerts.AlertProps{
					AlertType: alerts.WarningAlert,
					Heading:   "Invalid credentials",
				}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			for _, formFieldSelector := range props.FormFieldOrder {
				templ_7745c5c3_Err = formfield.Show(formfield.FormFieldProps{
					FormElementProps: base.FormElementProps{
						ElementProps: base.ElementProps{
							AdditionalClasses: []string{"mb-3"},
						},
					},
					FloatingLabels: true,
					Label: formlabel.Show(formlabel.FormLabelProps{
						For:  props.FormFields[formFieldSelector].FieldName,
						Text: props.FormFields[formFieldSelector].FieldLabel,
					}),
					Field: inputfield.Show(inputfield.InputProps{
						FormElementProps: base.FormElementProps{
							ElementProps: base.ElementProps{
								Id: props.FormFields[formFieldSelector].FieldName,
							},
						},
						Value:       props.FormFields[formFieldSelector].FieldValue,
						Placeholder: props.FormFields[formFieldSelector].FieldPlaceholder,
						Type:        props.FormFields[formFieldSelector].FieldType,
						// ValidationState: props.FormFields[formFieldSelector].FieldValidationState,
						FieldValidationFeedbackMessage: props.FormFields[formFieldSelector].FieldValidationFeedbackMessage,
					}),
				}).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			return nil
		})
		templ_7745c5c3_Err = form.Show(form.FormProps{
			Action: form.FormAction{
				Method: http.MethodPost,
				Action: "/htmx",
				Actions: form.FormActionsMap{
					form.PrimaryFormAction:   {Name: "Submit"},
					form.SecondaryFormAction: {Name: "Cancel"},
				},
			},
			FloatingLabels: true,
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
