// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package defaulttemplate

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/chrisbward/templstrap.io/pkg/components/breadcrumb"
	"github.com/chrisbward/templstrap.io/pkg/components/breadcrumb/breadcrumbitem"
	"github.com/chrisbward/templstrap.io/pkg/components/navbar"
	"github.com/chrisbward/templstrap.io/pkg/components/navbar/navitem"
)

type DefaultTemplateProps struct {
	SiteNavigation            templ.Component
	BreadCrumbItems           []*breadcrumbitem.BreadcrumbItemProps
	ComponentsNavItems        []*navitem.NavItemProps
	ComponentsNavItemsSidebar []navitem.NavItemProps
}

var components = []string{
	"accordion",
	"alerts",
	"badge",
	"breadcrumb",
	"card",
}

func (dtp DefaultTemplateProps) GetComponentLinksForMainNavigation() (items []*navitem.NavItemProps) {

	for _, componentName := range components {
		dtp.ComponentsNavItems = append(dtp.ComponentsNavItems, &navitem.NavItemProps{
			Name: componentName,
			Link: fmt.Sprintf("/components/%s", componentName),
		})
	}
	items = dtp.ComponentsNavItems
	return

}

func Show(props DefaultTemplateProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container-fluid\"><div class=\"row mb-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = navbar.Show(navbar.NavbarProps{
			Brand: &navbar.BrandProps{
				BrandName: "TemplStrap.io",
				BrandLink: "/",
			},
			NavItems: props.ComponentsNavItems,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"row\"><!-- Left Column --><div class=\"col-md-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.BreadCrumbItems != nil {
			templ_7745c5c3_Err = breadcrumb.Show(breadcrumb.BreadcrumbProps{
				BreadcrumbItems: props.BreadCrumbItems,
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
