// Code generated by MockGen. DO NOT EDIT.
// Source: ../controllers/formcontroller/formcontroller.go
//
// Generated by this command:
//
//	mockgen -package mock_formcontroller -destination=../controllers/formcontroller/mocks/mock_formcontroller.go -source=../controllers/formcontroller/formcontroller.go -typed
//
// Package mock_formcontroller is a generated GoMock package.
package mock_formcontroller
